server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/masterly_db
    username: masterly_user
    password: masterly_password

  flyway:
    enabled: true
    locations:
      - classpath:db/production-migration
      - classpath:db/migration

database:
  admin:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

jwt:
  secret: your-secret-key-for-jwt-token-change-in-production
  expiration: 86400000